version: "2.4"

services:
  app-hizz-web:
    build:
      context: .
      dockerfile: docker/hizz-web/python/Dockerfile
    restart: always
    ports:
      - "8081"
      - "8000"
    volumes:
      - ./app:/app
      - /opt/vida/hizz-web/customers_data:/customers_data
    #      - ./uploads:/uploads
    #      - /opt/vida/dev/customers_data:/customers_data

    volumes_from:
      - container:traefik_vimmodadev

    command: sh -c "python manage.py wait_for_db && uwsgi --socket :8081 --http :8000 --buffer-size=32768 --module app.wsgi"
    #      sh -c "python manage.py wait_for_db && uwsgi --http :8000 --module app.wsgi"
    #      sh -c "python manage.py wait_for_db && uwsgi --ini uwsgi.ini uwsgi --module app.wsgi"
    #      gunicorn -w 4 app.wsgi -b 0.0.0.0:8080"
    env_file:
      - ./envfiles/.hizz-web_envfile

    depends_on:
      - db-hizz-web
    labels:
      # api
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.apivrdrvida24.rule=Host(`apirdr.vida24.de`) "
      - "traefik.http.routers.apivrdrvida24.middlewares=secureHeaders@file"
      - "traefik.http.services.apivrdrvida24.loadbalancer.server.port=8000"
      - "traefik.http.routers.apivrdrvida24.tls.certresolver=letsencrypt"
      - "traefik.http.routers.apivrdrvida24.priority=899"
      - "traefik.http.routers.apivrdrvida24.tls=true"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_hizz-web
#      - VIRTUAL_HOST=apirdr.vidadev.de
#      - VIRTUAL_PROTO= uwsgi
#      - LETSENCRYPT_HOST=apirdr.vidadev.de
#      - LETSENCRYPT_EMAIL=mm@vimmoda.com

  db-hizz-web:
    image: store/oracle/mysql-enterprise-server:5.7
    container_name: db-mysql-hizz-web
    restart: always
    volumes:
      - ./sql_scripts/dev/:/docker-entrypoint-initdb.d/
      - /opt/docker-containers/data/hizz-web/mysql_data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Xb44StagS#!
      - MYSQL_USER=vidauser
      - MYSQL_PASSWORD=Xb44StagS#!
networks:
  default:
    external:
#      name: nginx-proxy
      name: traefik-proxy

