version: "2.4"

services:
  app-hizz-web:
    build:
      context: .
      dockerfile: docker/local/python/Dockerfile
    ports:
      - "8081"
    volumes:
      - ./aahizz:/aahizz

    volumes_from:
      - container:nginx-proxy


    command: sh -c "python manage.py wait_for_db && uwsgi --socket :8081 --http :8000 --buffer-size=32768 --module app.wsgi"
#    command: sh -c "python manage.py wait_for_db && uwsgi  --http :8081 --module app.wsgi" # not working with nginx proxy
#      sh -c "python manage.py wait_for_db && uwsgi --http :8000 --module app.wsgi"
#      sh -c "python manage.py wait_for_db && uwsgi --ini uwsgi.ini uwsgi --module app.wsgi"
#      gunicorn -w 4 app.wsgi -b 0.0.0.0:8080"

    env_file:
      - ./envfiles/.local_envfile

    depends_on:
      - db-hizz-web
#      - nginx

    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_local
      - VIRTUAL_HOST=api.hizz.lvh.me
      - VIRTUAL_PROTO= uwsgi
      - LETSENCRYPT_HOST=api.hizz.lvh.me
      - LETSENCRYPT_EMAIL=ferid.maghraoui@gmail.com

  db-hizz-web:
    image: store/oracle/mysql-enterprise-server:5.7
    container_name: db-mysql-hizz-local
    restart: always
    volumes:
      - ./sql_scripts/local/:/docker-entrypoint-initdb.d/
      - my-local-datavolume:/var/lib/mysql
#    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    env_file:
      - ./envfiles/.local_envfile
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
volumes:
  my-local-datavolume:
networks:
  default:
    external:
      name: nginx-proxy
